# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='name',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='song',
            name='neg_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='pos',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='song',
            name='pos_votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
